watch_config_changes: True
rendering_backend: V2

enable_logging: True

global:
  border_width: 1
  border_offset: -1
  border_radius: Square
  border_z_order: AboveWindow

  active_color: "#EFEFEF"
  inactive_color: "#5F5F5F"

  initialize_delay: 0
  unminimize_delay: 0

  follow_native_border: True

  effects:
    enabled: False
    active:
      - type: Shadow
        blur: 1
        spread: 3
        opacity: 1
    inactive:
      - type: Shadow
        blur: 1
        spread: 3
        opacity: 1

window_rules:
  - match: Class
    name: "Windows.UI.Core.CoreWindow"
    enabled: False

  - match: Class
    name: "XamlExplorerHostIslandWindow"
    enabled: False

  - match: Process
    name: "zebar"
    enabled: False

  - match: Title
    name: "komorebi-bar"
    enabled: False

  - match: Title
    name: "keyviz"
    enabled: False

  - match: Title
    name: "Picture-in-Picture"
    enabled: False
  
  - match: Process
    name: "tacky-borders"
    enabled: False
  
  - match: Process
    name: "seelen-ui"
    enabled: False

  - match: Class
    name: "#32770 (Dialog)"
    enabled: True
