watch_config_changes: True
rendering_backend: Legacy

enable_logging: True

global:
  border_width: 2
  border_offset: -1
  border_radius: Square
  border_z_order: AboveWindow

  active_color: "#DADADA"
  inactive_color: "#5F5F5F"

  initialize_delay: 0
  unminimize_delay: 0

  follow_native_border: False

  effects:
    enabled: False
    active:
      - type: Shadow
        blur: 3
        spread: 3
        opacity: 0.9
    inactive:
      - type: Shadow
        blur: 2
        spread: 2
        opacity: 0.6

window_rules:
  - match: Class
    name: "Windows.UI.Core.CoreWindow"
    enabled: False

  - match: Class
    name: "XamlExplorerHostIslandWindow"
    enabled: False

  - match: Process
    name: "zebar"
    enabled: False

  - match: Title
    name: "komorebi-bar"
    enabled: False

  - match: Title
    name: "keyviz"
    enabled: False

  - match: Title
    name: "Picture-in-Picture"
    enabled: False
  
  - match: Process
    name: "tacky-borders"
    enabled: False
  
  - match: Process
    name: "seelen-ui"
    enabled: False

  - match: Process
    name: "Cloudflare WARP"
    enabled: False